version: '3'
services:
  app:
    build: app
    volumes:
      - ${SRC_DIR}:/var/www/html
    restart: always

  web:
    build: web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SRC_DIR}:/var/www/html
      - ./web/default.conf.template:/etc/nginx/conf.d/default.conf.template
      - ./web/site.conf.template:/etc/nginx/conf.d/site.conf.template
      - ./web/certs:/etc/nginx/conf.d/certs
    environment:
      - HOST=${HOST}
      - DOLLAR=$$
    command: >
      /bin/sh -c "/usr/bin/envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf
      && /usr/bin/envsubst < /etc/nginx/conf.d/site.conf.template > /etc/nginx/conf.d/site.conf
      && exec nginx -g 'daemon off;'"
    depends_on:
      - app
    restart: always